version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hope-in-numbers-daily-verse-sender"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-139cq5tfaxqkk"
s3_prefix = "hope-in-numbers-daily-verse-sender"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
