Transform: AWS::Serverless-2016-10-31
Resources:
  HopeInNumbersDailyVersesDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: month-day
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: month-day
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  HopeInNumbersDailyVerseSender:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: HopeInNumbersDailyVerseSender
      CodeUri: src/Function
      Handler: handler.handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 900
      Tracing: Active
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
  HopeInNumbersDailyVerseSenderLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${HopeInNumbersDailyVerseSender}